/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.valledor.msp.basicchat;

import org.bukkit.plugin.java.JavaPlugin;

public class BasicChat extends JavaPlugin {

    @Override
    public void onEnable() {

        super.getLogger().info("BasicChatPlugin enabled. woow");
        super.getCommand("looc").setExecutor(new LOOCCommand());
        super.getCommand("ooc").setExecutor(new OOCCommand());
    }

    @Override
    public void onDisable() {

        super.getLogger().info("BasicChatPlugin disabled.");
    }
}
